spring.application.name=SankalpApplication

server.port=${SERVER_PORT:8080}

# ==========================
# DATABASE CONFIGURATION
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sankalpapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pikachu@24680}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Razorpay Configuration
razorpay.key=${RAZORPAY_KEY:rzp_test_TCwY5LtRiOOXLt}
razorpay.secret=${RAZORPAY_SECRET:lc0gF2umqxn0lVCvRMwacux1}