spring.application.name=TestApplication

server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/testapplication?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=yogita123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Upload Folder
file.upload-dir=uploads/


# LOGGING
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Razorpay Configuration
razorpay.key=rzp_test_TCwY5LtRiOOXLt
razorpay.secret=lc0gF2umqxn0lVCvRMwacux1

# JWT
jwt.secret=TestApplicationSecretKey12345678901234567890
jwt.expiration=86400000

# JACKSON
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false


# TIMEZONE
spring.jackson.time-zone=Asia/Kolkata